services:
  - type: web
    name: ftn-hackathon
    env: node
    branch: main
    buildCommand: bun install && bun run build
    startCommand: node .output/server/index.mjs
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NITRO_PRESET
        value: render_com
      - key: VITE_API_URL
        value: https://calvaltec-backend.onrender.com
