/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarClaveRouteImport } from './routes/recuperar-clave'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated.reportes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated.perfil'
import { Route as AuthenticatedHistorialRouteImport } from './routes/_authenticated.historial'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated.empresas'
import { Route as AuthenticatedDiagnosticosRouteImport } from './routes/_authenticated.diagnosticos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCuestionarioRouteImport } from './routes/_authenticated.cuestionario'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedRecomendacionesAssessmentIdRouteImport } from './routes/_authenticated.recomendaciones.$assessmentId'
import { Route as AuthenticatedCumplimientoAssessmentIdRouteImport } from './routes/_authenticated.cumplimiento.$assessmentId'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarClaveRoute = RecuperarClaveRouteImport.update({
  id: '/recuperar-clave',
  path: '/recuperar-clave',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistorialRoute = AuthenticatedHistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiagnosticosRoute =
  AuthenticatedDiagnosticosRouteImport.update({
    id: '/diagnosticos',
    path: '/diagnosticos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCuestionarioRoute =
  AuthenticatedCuestionarioRouteImport.update({
    id: '/cuestionario',
    path: '/cuestionario',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecomendacionesAssessmentIdRoute =
  AuthenticatedRecomendacionesAssessmentIdRouteImport.update({
    id: '/recomendaciones/$assessmentId',
    path: '/recomendaciones/$assessmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCumplimientoAssessmentIdRoute =
  AuthenticatedCumplimientoAssessmentIdRouteImport.update({
    id: '/cumplimiento/$assessmentId',
    path: '/cumplimiento/$assessmentId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-clave': typeof RecuperarClaveRoute
  '/registro': typeof RegistroRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cuestionario': typeof AuthenticatedCuestionarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosticos': typeof AuthenticatedDiagnosticosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/cumplimiento/$assessmentId': typeof AuthenticatedCumplimientoAssessmentIdRoute
  '/recomendaciones/$assessmentId': typeof AuthenticatedRecomendacionesAssessmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recuperar-clave': typeof RecuperarClaveRoute
  '/registro': typeof RegistroRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/cuestionario': typeof AuthenticatedCuestionarioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diagnosticos': typeof AuthenticatedDiagnosticosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/historial': typeof AuthenticatedHistorialRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/cumplimiento/$assessmentId': typeof AuthenticatedCumplimientoAssessmentIdRoute
  '/recomendaciones/$assessmentId': typeof AuthenticatedRecomendacionesAssessmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-clave': typeof RecuperarClaveRoute
  '/registro': typeof RegistroRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/cuestionario': typeof AuthenticatedCuestionarioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diagnosticos': typeof AuthenticatedDiagnosticosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/historial': typeof AuthenticatedHistorialRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/_authenticated/cumplimiento/$assessmentId': typeof AuthenticatedCumplimientoAssessmentIdRoute
  '/_authenticated/recomendaciones/$assessmentId': typeof AuthenticatedRecomendacionesAssessmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-clave'
    | '/registro'
    | '/admin'
    | '/cuestionario'
    | '/dashboard'
    | '/diagnosticos'
    | '/empresas'
    | '/historial'
    | '/perfil'
    | '/reportes'
    | '/oauth/callback'
    | '/cumplimiento/$assessmentId'
    | '/recomendaciones/$assessmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recuperar-clave'
    | '/registro'
    | '/admin'
    | '/cuestionario'
    | '/dashboard'
    | '/diagnosticos'
    | '/empresas'
    | '/historial'
    | '/perfil'
    | '/reportes'
    | '/oauth/callback'
    | '/cumplimiento/$assessmentId'
    | '/recomendaciones/$assessmentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/recuperar-clave'
    | '/registro'
    | '/_authenticated/admin'
    | '/_authenticated/cuestionario'
    | '/_authenticated/dashboard'
    | '/_authenticated/diagnosticos'
    | '/_authenticated/empresas'
    | '/_authenticated/historial'
    | '/_authenticated/perfil'
    | '/_authenticated/reportes'
    | '/oauth/callback'
    | '/_authenticated/cumplimiento/$assessmentId'
    | '/_authenticated/recomendaciones/$assessmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarClaveRoute: typeof RecuperarClaveRoute
  RegistroRoute: typeof RegistroRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-clave': {
      id: '/recuperar-clave'
      path: '/recuperar-clave'
      fullPath: '/recuperar-clave'
      preLoaderRoute: typeof RecuperarClaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/historial': {
      id: '/_authenticated/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof AuthenticatedHistorialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diagnosticos': {
      id: '/_authenticated/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/diagnosticos'
      preLoaderRoute: typeof AuthenticatedDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cuestionario': {
      id: '/_authenticated/cuestionario'
      path: '/cuestionario'
      fullPath: '/cuestionario'
      preLoaderRoute: typeof AuthenticatedCuestionarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recomendaciones/$assessmentId': {
      id: '/_authenticated/recomendaciones/$assessmentId'
      path: '/recomendaciones/$assessmentId'
      fullPath: '/recomendaciones/$assessmentId'
      preLoaderRoute: typeof AuthenticatedRecomendacionesAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cumplimiento/$assessmentId': {
      id: '/_authenticated/cumplimiento/$assessmentId'
      path: '/cumplimiento/$assessmentId'
      fullPath: '/cumplimiento/$assessmentId'
      preLoaderRoute: typeof AuthenticatedCumplimientoAssessmentIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCuestionarioRoute: typeof AuthenticatedCuestionarioRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiagnosticosRoute: typeof AuthenticatedDiagnosticosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedHistorialRoute: typeof AuthenticatedHistorialRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedCumplimientoAssessmentIdRoute: typeof AuthenticatedCumplimientoAssessmentIdRoute
  AuthenticatedRecomendacionesAssessmentIdRoute: typeof AuthenticatedRecomendacionesAssessmentIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCuestionarioRoute: AuthenticatedCuestionarioRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiagnosticosRoute: AuthenticatedDiagnosticosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedHistorialRoute: AuthenticatedHistorialRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedCumplimientoAssessmentIdRoute:
    AuthenticatedCumplimientoAssessmentIdRoute,
  AuthenticatedRecomendacionesAssessmentIdRoute:
    AuthenticatedRecomendacionesAssessmentIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarClaveRoute: RecuperarClaveRoute,
  RegistroRoute: RegistroRoute,
  OauthCallbackRoute: OauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
